name: 'Submodule Notify Parent'

on:
  push:
    branches:
      - main    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  notify:
    name: 'Submodule Notify Parent'
    runs-on: windows-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: cmd

    steps:
    - name: Github REST API Call
      env:
        CI_TOKEN: ${{ secrets.CI_TOKEN }}
        PARENT_REPO: macinn/skrzypczakm
        PARENT_BRANCH: main
        WORKFLOW_ID: 80738242
      run: |
        curl -X POST --http1.1 -H "Accept: application/vnd.github.v3+json" -H "Authorization: token %CI_TOKEN%" https://api.github.com/repos/%PARENT_REPO%/actions/workflows/%WORKFLOW_ID%/dispatches -d "{\"ref\":\"%PARENT_BRANCH%\"}"
